[paths]
config_folder = "${XDG_CONFIG_HOME}"
compose_folder = "${XDG_CONFIG_HOME}/compose"

[ui]
theme = "DockSTARTer"
borders = "true"
line_characters = "true"
scrollbar = "true"
shadow = "true"

[pm]
package_manager = ""
