#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

integrate_homepage() {
	# integrate_homepage
	# Generates the gethomepage/homepage YAML configs (services.yaml +
	# widgets) referencing every enabled app's collected key. Skips if
	# services.yaml already exists.
	{
		printf '\n=== integrate_homepage @ %s ===\n' "$(date -Iseconds)"
	} >> "${INTEGRATION_LOG_FILE}" 2>&1 || true

	local hp_enabled=""
	run_script 'env_get_into' hp_enabled "HOMEPAGE__ENABLED" 2> /dev/null || true
	is_true "${hp_enabled}" || {
		notice "Homepage is not enabled; skipping integrate_homepage."
		return 0
	}

	local config_dir="${DOCKER_VOLUME_CONFIG}/homepage"
	local services_file="${config_dir}/services.yaml"
	if [[ -f ${services_file} ]]; then
		notice "Homepage services.yaml already exists; skipping (won't overwrite)."
		return 0
	fi
	mkdir -p "${config_dir}" || return 0

	local domain=""
	run_script 'env_get_into' domain "GLOBAL_DOMAIN" 2> /dev/null || true

	local -A widget_kind=(
		["sonarr"]="sonarr"
		["radarr"]="radarr"
		["lidarr"]="lidarr"
		["prowlarr"]="prowlarr"
		["sabnzbd"]="sabnzbd"
		["qbittorrent"]="qbittorrent"
		["jellyfin"]="jellyfin"
		["jackett"]="jackett"
		["nzbhydra2"]="nzbhydra2"
	)

	{
		printf '# Auto-generated by DockSTARTer integrate_homepage.\n'
		printf '\n- Media:\n'
		local slug enabled key href
		for slug in "${!widget_kind[@]}"; do
			enabled=""
			run_script 'env_get_into' enabled "${slug^^}__ENABLED" 2> /dev/null || true
			is_true "${enabled}" || continue
			key=""
			run_script 'api_key_get_into' key "${slug}.api_key" 2> /dev/null || true
			if [[ -n ${domain} ]]; then
				href="https://${slug}.${domain}"
			else
				href="http://${slug}:80"
			fi
			printf '    - %s:\n' "${slug}"
			printf '        href: %s\n' "${href}"
			printf '        widget:\n'
			printf '          type: %s\n' "${widget_kind[$slug]}"
			printf '          url: %s\n' "${href}"
			if [[ -n ${key} ]]; then
				printf '          key: %s\n' "${key}"
			fi
		done
	} > "${services_file}"

	chmod 600 "${services_file}" || true
	notice "Wrote Homepage services.yaml to ${services_file}."
}

test_integrate_homepage() {
	warn "CI does not test integrate_homepage (requires a running stack)."
}
