#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

integrate_recyclarr() {
	# integrate_recyclarr
	# Generates ${DOCKER_VOLUME_CONFIG}/recyclarr/recyclarr.yml with
	# Trash Guides quality profiles for each enabled arr, substituting
	# the collected API keys. Skips existing file (won't overwrite).
	{
		printf '\n=== integrate_recyclarr @ %s ===\n' "$(date -Iseconds)"
	} >> "${INTEGRATION_LOG_FILE}" 2>&1 || true

	local recyclarr_enabled=""
	run_script 'env_get_into' recyclarr_enabled "RECYCLARR__ENABLED" 2> /dev/null || true
	is_true "${recyclarr_enabled}" || {
		notice "Recyclarr is not enabled; skipping integrate_recyclarr."
		return 0
	}

	local config_dir="${DOCKER_VOLUME_CONFIG}/recyclarr"
	local config_file="${config_dir}/recyclarr.yml"
	if [[ -f ${config_file} ]]; then
		notice "Recyclarr config already exists at ${config_file}; skipping (won't overwrite)."
		return 0
	fi

	mkdir -p "${config_dir}" || {
		warn "Could not create ${config_dir}; skipping."
		return 0
	}

	local sonarr_key="" radarr_key=""
	run_script 'api_key_get_into' sonarr_key "sonarr.api_key" 2> /dev/null || true
	run_script 'api_key_get_into' radarr_key "radarr.api_key" 2> /dev/null || true

	{
		printf '# Auto-generated by DockSTARTer integrate_recyclarr.\n'
		printf '# Sync TRaSH Guides quality profiles + custom formats.\n\n'
		if [[ -n ${sonarr_key} ]]; then
			printf 'sonarr:\n'
			printf '  main:\n'
			printf '    base_url: http://sonarr:8989\n'
			printf '    api_key: %s\n' "${sonarr_key}"
			printf '    quality_definition:\n      type: series\n\n'
		fi
		if [[ -n ${radarr_key} ]]; then
			printf 'radarr:\n'
			printf '  main:\n'
			printf '    base_url: http://radarr:7878\n'
			printf '    api_key: %s\n' "${radarr_key}"
			printf '    quality_definition:\n      type: movie\n'
		fi
	} > "${config_file}"

	chmod 600 "${config_file}" || true
	notice "Wrote Recyclarr config to ${config_file}."
}

test_integrate_recyclarr() {
	warn "CI does not test integrate_recyclarr (requires a running stack)."
}
