#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

integrate_grafana_datasources() {
	# integrate_grafana_datasources
	# Writes Grafana provisioning YAML at
	# ${DOCKER_VOLUME_CONFIG}/grafana/provisioning/datasources/influxdb.yaml
	# referencing the collected InfluxDB admin token. Grafana picks
	# this up on next restart.
	{
		printf '\n=== integrate_grafana_datasources @ %s ===\n' "$(date -Iseconds)"
	} >> "${INTEGRATION_LOG_FILE}" 2>&1 || true

	local grafana_enabled="" influx_enabled=""
	run_script 'env_get_into' grafana_enabled "GRAFANA__ENABLED" 2> /dev/null || true
	run_script 'env_get_into' influx_enabled "INFLUXDB__ENABLED" 2> /dev/null || true
	is_true "${grafana_enabled}" || {
		notice "Grafana is not enabled; skipping grafana datasource provisioning."
		return 0
	}
	is_true "${influx_enabled}" || {
		notice "InfluxDB is not enabled; nothing to provision into Grafana."
		return 0
	}

	local token
	if ! run_script 'api_key_get_into' token "influxdb.admin_token"; then
		warn "InfluxDB admin token not collected; cannot provision Grafana datasource."
		return 0
	fi

	local provisioning_dir="${DOCKER_VOLUME_CONFIG}/grafana/provisioning/datasources"
	mkdir -p "${provisioning_dir}" || {
		warn "Could not create ${provisioning_dir}."
		return 0
	}
	local file="${provisioning_dir}/influxdb.yaml"

	cat > "${file}" <<EOF
# Auto-generated by DockSTARTer integrate_grafana_datasources.
apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: dockstarter
      defaultBucket: dockstarter
      tlsSkipVerify: true
    secureJsonData:
      token: ${token}
    editable: true
EOF
	chmod 600 "${file}" || true
	notice "Wrote Grafana InfluxDB datasource provisioning to ${file}."
}

test_integrate_grafana_datasources() {
	warn "CI does not test integrate_grafana_datasources (requires a running stack)."
}
