#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

docker_overrides_initialize() {
    local ACTIONS=0
    local DOCKER_OVERRIDES_DIR
    DOCKER_OVERRIDES_DIR=$(run_script 'env_get' DOCKEROVERRIDESDIR)
    info "Running Docker Overrides Initialization."
    if [[ -z ${DOCKER_OVERRIDES_DIR} ]]; then
        run_script 'env_update'
        DOCKER_OVERRIDES_DIR=$(run_script 'env_get' DOCKEROVERRIDESDIR)
        ACTIONS=$((ACTIONS + 1))
    fi
    # Check for the directory and create it if it doesn't exist
    if [[ ! -d ${DOCKER_OVERRIDES_DIR} ]]; then
        info "${DOCKER_OVERRIDES_DIR}/ not found. Creating..."
        mkdir -p "${DOCKER_OVERRIDES_DIR}/" || fatal "Unable to create ${DOCKER_OVERRIDES_DIR}/"
        ACTIONS=$((ACTIONS + 1))
    fi
    # Move the user's existing docker-compose.override.yml, if it exists
    if [[ -f "${SCRIPTPATH}/compose/docker-compose.override.yml" ]]; then
        if ! grep -q 'GENERATED BY DOCKSTARTER' "${SCRIPTPATH}/compose/docker-compose.override.yml"; then
            info "Found user-created docker-compose.overrides.yml file."
            run_script 'override_backup'
            warn "Moving docker-compose.overrides.yml to ${DOCKER_OVERRIDES_DIR}/docker-compose.override.original.yml"
            mv "${SCRIPTPATH}/compose/docker-compose.override.yml" "${DOCKER_OVERRIDES_DIR}/docker-compose.override.original.yml" || fatal "Unable to move user-created docker-compose.overrides.yml file."
            ACTIONS=$((ACTIONS + 1))
        fi
    fi
    if [[ ${ACTIONS} -eq 0 ]]; then
        notice "Docker Overrides already initialized!"
    else
        notice "Docker Overrides successfully initialized!"
    fi
}

test_docker_overrides_initialize() {
    run_script 'docker_overrides_initialize'
}
